apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop
  name: shop
spec:
  type: NodePort
  ports:
  - name: "shop-service"
    port: 8080
    targetPort: 80
    nodePort: 31005
  selector:
    app: shop
